### ISSUE TITLE
informações?

### ISSUE THREAD

**Issue by arademaker** [lexml/wiki#1]
O readme do repositório fala que teríamos aqui informações sobre os projetos relacionados ao LEXML, mas nas duas páginas do wiki constam apenas 1-2 itens de configuração do GIT e Marven. Imagino que a documentação ainda esteja em construção. É isso? Quais os planos?

**Comment by joaoli13** [comment]
Prof. Alexandre,
  Já encaminhei email com as minhas informações de contato.
Abs

Joao Lima

**Comment by arademaker** [comment]
Obrigado.
